<?php

/**
 * Implements hook_ckeditor_plugin()
 * 
 * @return type
 */
function ckeditor_bootstrap_ckeditor_plugin() {
  $plugins = array();
  $plugins['trifold'] = array(
    'name' => 'trifold',
    'desc' => t('Bootstrap Trifold Plugin'),
    'path' => drupal_get_path('module', 'ckeditor_bootstrap') . '/plugins/trifold/',
    'buttons' => array(
      'Trifold' => array('label' => 'Trifold', 'icon' => 'icons/trifold.png'),
    )
  );
  $plugins['featurette'] = array(
    'name' => 'featurette',
    'desc' => t('Bootstrap Featurette Plugin'),
    'path' => drupal_get_path('module', 'ckeditor_bootstrap') . '/plugins/featurette/',
    'buttons' => array(
      'Featurette' => array('label' => 'Featurette', 'icon' => 'icons/featurette.png'),
    )
  );
  $plugins['carousel'] = array(
    'name' => 'carousel',
    'desc' => t('Bootstrap Carousel Plugin'),
    'path' => drupal_get_path('module', 'ckeditor_bootstrap') . '/plugins/carousel/',
    'buttons' => array(
      'Carousel' => array('label' => 'Carousel', 'icon' => 'icons/carousel.png'),
    )
  );
  $plugins['jumbotron'] = array(
    'name' => 'jumbotron',
    'desc' => t('Bootstrap Jumbotron Plugin'),
    'path' => drupal_get_path('module', 'ckeditor_bootstrap') . '/plugins/jumbotron/',
    'buttons' => array(
      'Jumbotron' => array('label' => 'Jumbotron', 'icon' => 'icons/jumbotron.png'),
    )
  );
  return $plugins;
}
