<?php

/**
 * Implements hook_theme_registry_alter().
 *
 * @var array $theme_registry
 */
function devconnect_faq_ext_theme_registry_alter(&$theme_registry) {
  $faq_ext_path = drupal_get_path('module', 'devconnect_faq_ext') . '/includes';
  $faq_path = drupal_get_path('module', 'faq') . '/includes';

  $theme_registry['faq_category_questions_top']['file'] = "$faq_path/faq.questions_top.inc";
  $theme_registry['faq_category_questions_top']['template'] = "$faq_ext_path/dc-faq-category-questions-top";
  unset ($theme_registry['faq_category_questions_top']['path']);

  $theme_registry['faq_category_questions_top_answers']['file'] = "$faq_path/faq.questions_top.inc";
  $theme_registry['faq_category_questions_top_answers']['template'] = "$faq_ext_path/dc-faq-category-questions-top-answers";
  unset ($theme_registry['faq_category_questions_top_answers']['path']);
}

/**
 * Implements hook_menu_alter().
 * @param $items
 */
function devconnect_faq_ext_menu_alter(&$items) {
  $items['faq']['type'] = MENU_CALLBACK;
}


