<?php
// @todo: Investigate and document the exact changes in the template files,
//        and see if less drastic measures can be taken instead.

/**
 * Implements hook_theme_registry_alter().
 *
 * @todo: see if we can just alter individual members of the theme registry items,
 *        instead of overwriting the entire item. For example, try setting
 *        $theme_registry['faq_category_questions_top']['file'].
 */
function devconnect_faq_ext_theme_registry_alter(&$theme_registry) {
  $faq_ext_path = drupal_get_path('module', 'devconnect_faq_ext') . '/includes/';
  $theme_registry['faq_category_questions_top'] = array(
    'file' => $faq_ext_path . 'faq.questions_top.inc',
    'template' => $faq_ext_path . 'dc-faq-category-questions-top',
    'arguments' => array(
      'data' => NULL,
      'display_header' => 0,
      'category_display' => NULL,
      'term' => NULL,
      'class' => NULL,
      'parent_term' => NULL
    ),
    'preprocess functions' => array(
      0 => 'templete_preprocess', // todo: check to see if this is a typo
      1 => 'phptemplate_preprocess_faq_category_questions_top',
    ),

  );
  $theme_registry['faq_category_questions_top_answers'] = array(
    'file' => $faq_ext_path . 'faq.questions_top.inc',
    'template' => $faq_ext_path . 'dc-faq-category-questions-top-answers',
    'arguments' => array(
      'data' => NULL,
      'display_header' => 0,
      'category_display' => NULL,
      'term' => NULL,
      'class' => NULL,
      'parent_term' => NULL
    ),
    'preprocess functions' => array(
      0 => 'templete_preprocess',
      1 => 'phptemplate_preprocess_faq_category_questions_top_answers',
    ),
  );
}

/**
 * Implements hook_menu_alter().
 * @param $items
 */
function devconnect_faq_ext_menu_alter(&$items) {
  $items['faq']['type'] = MENU_CALLBACK;
}


