<?php

/**
 * Implementation of hook_uninstall()
 *
 */
function statsd_uninstall() {

  variabel_del('statsd_enabled');
  variable_del('statsd_host');
  variable_del('statsd_port');
  variable_del('statsd_user_events');
  variable_del('statsd_performance_events');
  variable_del('statsd_watchdog_events');
  variable_del('statsd_watchdog_level');
  variable_del('statsd_sample_rate');
  variable_del('statsd_prefix');
  variable_del('statsd_suffix');

}