<?php

/**
 * Implements hook_init().
 *
 * Registers our custom autoloader.
 */
function devconnect_init() {
  static $already_booted = FALSE;
  if (!$already_booted) {
    if (!module_exists('libraries')) {
      module_load_include('module', 'libraries');
    }
    $lib_dir = libraries_get_path('mgmt-api-php-sdk');
    // During migrations, we might get an empty lib dir due to bad cached
    // install_profile value.
    if (empty($lib_dir)) {
      $lib_dir = 'profiles/apigee/libraries/mgmt-api-php-sdk';
    }
    require_once $lib_dir . '/vendor/autoload.php';
    $already_booted = TRUE;
    $key = variable_get('apigee_crypt_key', NULL);
    if (empty($key)) {
      $key = hash('SHA256', 'w3-Love_ap|s', TRUE);
    }
    Apigee\Util\Crypto::setKey($key);
  }
}

/**
 * Implements hook_menu_alter().
 *
 * Denies access to PHP execution URL in the devel module if it is enabled.
 *
 * @param $items
 */
function devconnect_menu_alter(&$items) {
  if (isset($items['devel/php'])) {
    $items['devel/php']['access callback'] = FALSE;
  }
}

function devconnect_menu() {
  $items = array();
  $items['admin/config/devconnect'] = array(
    'title' => 'Dev Portal Settings',
    'description' => 'Apigee Edge authentication settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devconnect_admin_form'),
    'access arguments' => array('administer organization settings'),
    'file' => 'devconnect.admin.inc'
  );
  return $items;
}

/**
 * Implements hook_filter_info_alter().
 *
 * Removes Display Suite and PHP Code filters if they are enabled, because
 * they expose security vulnerabilities.
 *
 * @TODO: devconnect_downloads currently relies on presence of ds_code filter.
 *        That module should be reworked so that this is no longer the case,
 *        then the conditional below should be removed.
 *
 * @param $info
 */
function devconnect_filter_info_alter(&$info) {
  if (!module_exists('devconnect_downloads')) {
    if (array_key_exists('ds_code', $info)) {
      unset ($info['ds_code']);
    }
  }
  if (array_key_exists('php_code', $info)) {
    unset($info['php_code']);
  }
}

/**
 * Implements hook_variable_group_info().
 *
 * @return array
 */
function devconnect_variable_group_info() {
  $groups['devconnect'] = array(
    'title' => t('Devconnect settings'),
    'description' => t('Settings for this Devconnect instance. Change these values with great care!'),
    'access' => 'administer organization settings',
    'path' => array('admin/config/devconnect'),
  );
  return $groups;
}

/**
 * Implements hook_permission().
 *
 * @return array
 */
function devconnect_permission() {
  return array(
    'administer organization settings' => array(
      'title' => 'Administer organization settings',
      'restrict access' => TRUE,
    ),
    'view devconnect errors' => array(
      'title' => 'View DevConnect error detail',
      'restrict access' => TRUE
    )
  );
}

/**
 * Implements hook_cron.
 */
function devconnect_cron() {
  // query & store environments
  try {
    $dev_app = new Apigee\ManagementAPI\DeveloperAppAnalytics(devconnect_default_org_config());
    $environments = $dev_app->queryEnvironments();
    variable_set('devconnect_org_environments', $environments);
  } catch (Exception $e) {
    // Ignore any exceptions thrown. These probably result from
    // misconfiguration of the endpoint.
  }
}


/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function devconnect_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login') {
    $form['userpasswordlink'] = array(
      '#markup' => '<br>' . l('Forgot your password?', 'user/password') . '<br><br>',
      '#weight' => 100
    );
  }
}

/**
 * Implements hook_theme().
 *
 * @return array
 */
function devconnect_theme() {
  $items = array();
  $tpl_path = drupal_get_path('module', 'devconnect') . '/templates';
  $items['devconnect_error_inline'] = array(
    'path' => $tpl_path,
    'template' => 'devconnect_error_inline',
    'variables' => array('summary' => NULL, 'detail' => NULL),
  );
  $items['devconnect_error_message'] = array(
    'path' => $tpl_path,
    'template' => 'devconnect_error_message',
    'variables' => array('summary' => NULL, 'detail' => NULL, 'severity' => 'error'),
  );
  return $items;
}

/**
 * Backwards-compatibility wrapper for devconnect_default_org_config().
 *
 * Use devconnect_default_org_config() instead for all new code.
 *
 * @return \Apigee\Util\OrgConfig
 * @deprecated
 */
function devconnect_default_api_client() {
  return devconnect_default_org_config();
}

/**
 * Returns a wrapper around org connection settings.
 *
 * @param string $requested_org
 * @return Apigee\Util\OrgConfig
 */
function devconnect_default_org_config($requested_org = 'default') {
  static $configs = array();

  if (!array_key_exists($requested_org, $configs)) {
    // Make sure autoloader is run.
    devconnect_init();
    $settings = devconnect_get_org_settings();
    drupal_alter('devconnect_org_settings', $settings, $requested_org);

    $buildInfo = FALSE;
    if (file_exists(DRUPAL_ROOT . '/buildInfo')) {
      $buildInfo = DRUPAL_ROOT . '/buildInfo';
    }
    elseif (file_exists(DRUPAL_ROOT . '/profiles/apigee/buildInfo')) {
      $buildInfo = DRUPAL_ROOT . '/profiles/apigee/buildInfo';
    }
    $user_agent = FALSE;
    if ($buildInfo) {
      $fp = fopen($buildInfo, 'r');
      $line = trim(fgets($fp));
      fclose($fp);
      if (preg_match('!([0-9.]+)$!', $line, $matches)) {
        $user_agent = 'DevPortal/' . $matches[1];
      }
    }
    if (!$user_agent) {
      $info = system_get_info('module', 'devconnect');
      $user_agent = 'devconnect/' . $info['version'];
    }

    $logger = new Apigee\Drupal\WatchdogLogger();
    $logger::setLogThreshold($settings['log_threshold']);
    $user_mail = user_is_logged_in() ? $GLOBALS['user']->mail : NULL;

    $adapter = new \Guzzle\Log\PsrLogAdapter($logger);
    $message = '<pre>' . \Guzzle\Log\MessageFormatter::DEBUG_FORMAT . '</pre>';
    $guzzle_log_plugin = new \Guzzle\Plugin\Log\LogPlugin($adapter, $message);

    $options = array(
      'logger' => $logger,
      'user_mail' => $user_mail,
      'subscribers' => array($guzzle_log_plugin),
      'http_options' => array(
        'connection_timeout' => intval($settings['connection_timeout']),
        'timeout' => intval($settings['request_timeout'])
      ),
      'user_agent' => $user_agent,
      'variable_store' => new Apigee\Drupal\VariableCache(),
      'referer' => url($_GET['q'], array('absolute' => TRUE))
    );
    if (function_exists('devconnect_debug_register')) {
      $options['debug_callbacks'] = array('devconnect_debug_register');
    }
    $configs[$requested_org] = new Apigee\Util\OrgConfig($settings['org'], $settings['endpoint'], $settings['user'], $settings['pass'], $options);
  }
  return $configs[$requested_org];
}

/**
 * Logs use of deprecated classes and functions (from pre-R21 days)
 * so that we can bring CS code up to current standards.
 */
function _devconnect_warn_deprecated() {
  if (version_compare(PHP_VERSION, '5.4', '>=')) {
    // Be more efficient when running PHP 5.4
    $backtrace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 2);
  }
  elseif (version_compare(PHP_VERSION, '5.3.6', '>=')) {
    // Sigh. Pull entire backtrace.
    $backtrace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
  }
  else {
    // We are dealing with real dinosaurs here. Be even less efficient.
    // PHP < 5.3.6 does not support any args to debug_backtrace().
    $backtrace = debug_backtrace();
  }
  $frame = $backtrace[1];

  if (isset($frame['class'])) {
    $subject = 'class ' . $frame['class'];
    $verb = 'instantiated';
  }
  else {
    $subject = 'function ' . $frame['function'];
    $verb = 'invoked';
  }
  $message = 'Deprecated %subject was %verb in file %file, line %line.';
  $args = array(
    '%subject' => $subject,
    '%verb' => $verb,
    '%file' => $frame['file'],
    '%line' => $frame['line']
  );
  devconnect_default_org_config()->logger->warning(t($message, $args), array('type' => 'devconnect'));
}

/**
 * Common error/notification handler for Edge faults.
 *
 * Invokes hook_devconnect_error_alter() to change how messages are displayed.
 *
 * @param int $error_code
 * @param string $summary
 * @param string $details
 * @param int $severity
 * @param int $display
 * @return bool|string
 */
function devconnect_notify($error_code, $summary, $details, $severity = Apigee\Util\ErrorHandling::SEVERITY_ERROR, $display = Apigee\Util\ErrorHandling::DISPLAY_MESSAGE) {
  drupal_alter('devconnect_error', $error_code, $summary, $details, $severity, $display);

  switch ($severity) {
    case Apigee\Util\ErrorHandling::SEVERITY_STATUS:
      $message_type = 'status';
      break;
    case Apigee\Util\ErrorHandling::SEVERITY_WARNING:
      $message_type = 'warning';
      break;
    default:
      $message_type = 'error';
      break;
  }
  if (!user_access('view devconnect errors')) {
    $details = NULL;
  }
  if ($display == Apigee\Util\ErrorHandling::DISPLAY_MESSAGE) {
    $formatted_message = theme('devconnect_error_message', array('summary' => $summary, 'detail' => $details));
    drupal_set_message($formatted_message, $message_type);
    return FALSE;
  }
  return theme('devconnect_error_inline', array(
    'summary' => $summary,
    'detail' => $details,
    'severity' => $message_type
  ));
}

function devconnect_get_debug_data() {
  return Apigee\Util\DebugData::toArray();
}

function &devconnect_get_org_settings() {
  devconnect_init();
  $custom_vars = variable_get('devconnect_org_settings', NULL);
  $settings_saved = !empty($custom_vars);
  if (!$settings_saved) {
    $possible_paths = array('sites/default/private', 'sites/default/files/private');
    $private_filesystem = variable_get('file_private_path', NULL);
    if ($private_filesystem) {
      array_unshift($possible_paths, $private_filesystem);
    }
    foreach ($possible_paths as $config_path) {
      if (file_exists("$config_path/config/active/devconnect.settings.yml")) {
        $custom_vars = Symfony\Component\Yaml\Yaml::parse("$config_path/config/active/devconnect.settings.yml");
        break;
      }
    }
  }
  if (empty($custom_vars)) {
    $custom_vars = array(
      'org' => '',
      'user' => '',
      'endpoint' => 'https://api.enterprise.apigee.com/v1',
      'pass' => '',
      'log_threshold' => 4,
      'connection_timeout' => 4,
      'request_timeout' => 4
    );
  }
  elseif (array_key_exists('pass', $custom_vars) && defined('MCRYPT_RIJNDAEL_128')) {
    try {
      $pass = Apigee\Util\Crypto::decrypt($custom_vars['pass']);
      if ($pass) {
        $custom_vars['pass'] = $pass;
      }
    } catch (Exception $e) {
    }
  }
  if (!$settings_saved) {
    variable_set('devconnect_org_settings', $custom_vars);
  }
  return $custom_vars;
}

/**
 * Implements hook_devconnect_monitor_event_info().
 *
 * Implementations return an associative array whose keys define
 * the unique alert name and whose values are an associative array of
 * properties for each path.  The alert name can be anything you want,
 * but should be prefixed with your module name to make sure it is
 * unique, such as "mymodule_overheating" and "mymodule_virusdetected".
 *
 * The array contains the following properties:
 *
 * description: A description of the alert, this can be anything to help
 * the end user.
 *
 * log_type: The watchdog type to match against when deciding to
 * sent out an alert.
 *
 * log_severity: The watchdog severity to match against when deciding to
 * sent out an alert.
 *
 */
function devconnect_devconnect_monitor_event_info() {
  return array(
    'edge_api_exceptions' => array(
      'description' => t('Edge API exceptions and timeouts.'),
      'log_type' => 'APIObject',
      'log_severity' => WATCHDOG_EMERGENCY,
    ),
  );
}

/**
 * Implements hook_update_projects_alter().
 *
 * Since we don't want jquery_update to update past version 2.3, we remove it
 * from the list of modules & themes that are candidates for update.
 *
 * @param $projects
 */
function devconnect_update_projects_alter(&$projects) {
  if (array_key_exists('jquery_update', $projects)) {
    unset($projects['jquery_update']);
  }
}

/**
 * Implements hook_theme_registry_alter().
 *
 * On Pantheon systems, register a preprocess callback for the status report.
 *
 * @param $theme_registry
 */
function devconnect_theme_registry_alter(&$theme_registry) {
  if (array_key_exists('PANTHEON_ENVIRONMENT', $_SERVER) && !module_exists('update')) {
    $theme_registry['status_report']['preprocess functions'][] = 'devconnect_preprocess_status_report';
  }
}

/**
 * Preprocess callback for status report.
 *
 * On Pantheon systems in which the Update module has not been explicitly
 * enabled, suppress the update-isn't-turned-on warning.
 *
 * @param $variables
 */
function devconnect_preprocess_status_report(&$variables) {
  foreach (array_keys($variables['requirements']) as $key) {
    if ($variables['requirements'][$key]['title'] == t('Update notifications') && $variables['requirements'][$key]['severity'] == 1) {
      unset($variables['requirements'][$key]);
      break;
    }
  }
}