<?php

function devconnect_default_structure_update_7001() {
  devconnect_default_structure_set_css_classes();
}

function devconnect_default_structure_set_css_classes() {
  if (module_exists("block_class")) {
    db_insert("block_class")
      ->fields(
      array(
        'css_class' => 'develop-with-these',
        'module' => 'devconnect_default_content',
        'delta' => 'develop-with-these'
      )
    )->execute();;
  }
}