<?php

/**
 * Clean up unused variables.
 */
function devconnect_user_update_7429() {
  variable_del('async_fail_notify_type');
  variable_del('async_fail_notify_mailto');
  variable_del('async_fail_notify_roles');
}

/**
 * Remove obsolete cache tables.
 */
function devconnect_user_update_7430() {
  $tables = array('dc_dev', 'dc_dev_attributes', 'dc_dev_companies');
  foreach ($tables as $table) {
    if (db_table_exists($table)) {
      db_drop_table($table);
    }
  }
}
