<?php


/**
 * If this is to work, it must run before field_import_html does,
 * as it scrapes data, but leaves the field utility to serialize it.
 *
 */
function import_html_scraping_rules_enable() {
  $weight = db_select('system', 's')
    ->fields('s', array('weight'))
    ->condition('name', 'field', '=')
    ->execute()
    ->fetchField();

  db_update('system')
    ->fields(array('weight' => $weight -1))
    ->condition('name', 'import_html_scraping_rules', '=')
    ->execute();
}
