<?php
/**
 * @file
 * Apigee Google tag manager.
 * 
 * Adds the google tag manager script to administration pages.
 */

/**
 * Implements hook_init().
 */
function apigee_gtm_init() {
  // Short circuit if we are not on an admin page.
  if (!path_is_admin(current_path())) {
    return;
  }

  // Default values.
  $version_number = '';
  $build_info_dir = DRUPAL_ROOT;
  $config = devconnect_default_org_config();
  $mail = $GLOBALS['user']->mail;

  // See if we can get a version number from buildInfo.
  if (!file_exists(DRUPAL_ROOT . '/buildInfo') && file_exists(DRUPAL_ROOT . '/profiles/apigee/buildInfo')) {
    $build_info_dir = DRUPAL_ROOT . '/profiles/apigee';
  }
  if (file_exists($build_info_dir . '/buildInfo')) {
    $fp = fopen($build_info_dir . '/buildInfo', 'r');
    $line = trim(fgets($fp));
    fclose($fp);
    if (preg_match('!([0-9.]{2,})$!', $line, $matches)) {
      $version_number = $matches[1];
    }
  }

  $data_layer = array(
    array(
      'component.name' => 'Developer Portal',
      'component.version' => $version_number,
      'user.email' => $mail,
      'organization.name' => $config->orgName,
      'pantheon.env' => isset($_ENV['PANTHEON_ENVIRONMENT']) ? $_ENV['PANTHEON_ENVIRONMENT'] : '',
      'pantheon.site' => isset($_ENV['PANTHEON_SITE_NAME']) ? $_ENV['PANTHEON_SITE_NAME'] : '',
    ),
  );

  if (strtolower(substr($mail, -11)) == '@apigee.com') {
    $data_layer[0]['user.internal'] = 'Internal';
  }

  drupal_add_js('var dataLayer = ' . json_encode($data_layer) . ';', 'inline');
  drupal_add_js(drupal_get_path('module', 'apigee_gtm') . '/apigee_gtm.js', 'file');
}
