<?php

/**
 * Implements hook_menu().
 *
 * @return array
 */
function devconnect_developer_apps_menu() {
  $items = array();
  $items['user/%user/apps'] = array(
    'title' => t('My Apps'),
    'page callback' => 'devconnect_developer_apps_getlist',
    'page arguments' => array(1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  $items['user/%user/app-detail/%'] = array(
    'title' => t('App Detail'),
    'page callback' => 'devconnect_developer_apps_detail',
    'page arguments' => array(1, 3),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'weight' => 0,
  );

  $items['user/%user/apps/add'] = array(
    'title' => t('Add New App'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devconnect_developer_apps_edit_form', 1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  $items['user/%user/apps/%/edit-app'] = array(
    'title' => t('Edit App'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devconnect_developer_apps_edit_form', 1, 3),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'weight' => 0,
  );

  $items['user/%user/apps/%/delete'] = array(
    'title' => t('Delete App'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devconnect_developer_app_delete_form'),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'weight' => 0,
  );

  return $items;
}

/**
 * Implements hook_variable_info().
 *
 * @param array $options
 *
 * @return array
 */
function devconnect_developer_apps_variable_info($options) {
  $variables['devconnect_show_analytics'] = array(
    'type' => 'boolean',
    'title' => t('Show Developer App performance tab?'),
    'default' => FALSE,
    'description' => t('When this value is enabled, the \'Performance\' tab will be displayed on the developer app detail page.'),
    'group' => 'devconnect'
  );
  $variables['devconnect_show_apiproduct_status'] = array(
    'type' => 'boolean',
    'title' => t('Show API Product status on the developer app list?'),
    'default' => FALSE,
    'description' => t('When this value is enabled, the app\'s status with each associated API Product is listed on the app listing page.'),
    'group' => 'devconnect'
  );
  return $variables;
}


/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function devconnect_developer_apps_theme($existing, $type, $theme, $path) {
  $items = array();
  $template_path = drupal_get_path('module', 'devconnect_developer_apps') . '/templates';


  $items['devconnect_developer_apps_list'] = array(
    'template' => 'devconnect_developer_apps_list',
    'arguments' => array('application_count' => 0, 'applications' => '', 'user' => NULL),
    'path' => $template_path
  );

  $items['devconnect_developer_credentials_list'] = array(
    'template' => 'devconnect_developer_credentials_list',
    'arguments' => array('credentials' => NULL),
    'path' => $template_path
  );

  $items['devconnect_developer_app'] = array(
    'template' => 'devconnect_developer_app',
    'arguments' => array(
      'account' => NULL,
      'access_type' => NULL,
      'callback_url' => NULL,
      'name' => NULL,
      'status' => NULL,
      'app_attributes' => array(),
      'credentials' => array(),
      'analytics_chart' => FALSE
    ),
    'path' => $template_path
  );

  $items['devconnect_developer_line_chart'] = array(
    'template' => 'devconnect_developer_line_chart',
    'arguments' => array(
      'x_translate' => 0,
      'vertical_lines' => array(),
      'horizontal_lines' => array(),
      'axis_overhang' => 5,
      'x_axis' => NULL,
      'y_axis' => NULL,
      'y_axis_title' => NULL,
      'data_lines' => array(),
      'actual_chart_width' => 0,
      'actual_chart_height' => 0,
    ),
    'path' => $template_path
  );

  return $items;
}

/**
 * Page callback for "My Apps"
 *
 * @param $user
 *
 * @return string
 * @throws Exception
 */
function devconnect_developer_apps_getlist($user) {
  $module_path = drupal_get_path('module', 'devconnect_developer_apps');
  $library_path = libraries_get_path('jquery.selectlist');
  drupal_add_js($library_path . '/scripts/jquery.selectlist.pack.js');
  drupal_add_css($library_path . '/css/selectlist.css');
  drupal_add_css("$module_path/devconnect_developer_apps.css");
  drupal_add_js("$module_path/devconnect_developer_apps.js");

  try {
    module_load_include('module', 'devconnect');
    $client = devconnect_default_api_client();
    $dc = new Apigee\ManagementAPI\DeveloperApp($client, $user->mail, (bool)variable_get('devconnect_appname_bug', FALSE));
    $app_names = $dc->get_list();
    if (count($app_names) == 0) {
      $parameters = array(
        'application_count' => 0,
        'applications' => array(),
        'user' => $user
      );
    }
    else {
      $rows = array();
      foreach ($app_names as $app_name) {
        $dc->load($app_name);
        $row = array(
          'app_name' => $dc->get_name(),
          'callback_url' => $dc->get_callback_url(),
          'attributes' => _devconnect_developer_apps_get_attributes($dc->get_attributes()),
          'credential' => array(
            'apiProducts' => $dc->get_credential_api_products(),
            'consumerKey' => $dc->get_consumer_key(),
            'consumerSecret' => $dc->get_consumer_secret(),
            'scopes' => $dc->get_credential_scopes(),
            'status' => $dc->get_credential_status()
          ),
          'delete_url' => 'user/' . $user->uid . '/apps/' . $app_name . '/delete',
          'edit_url' => 'user/' . $user->uid . '/apps/' . $app_name . '/edit-app'
        );
        $rows[] = $row;
      }
      $parameters = array(
        'application_count' => count($rows),
        'applications' => $rows,
        'user' => $user,
      );
    }
    // Invoke hook_devconnect_developer_app_list_alter() on this parm list.
    drupal_alter('devconnect_developer_app_list', $parameters);

    return theme('devconnect_developer_apps_list', $parameters);
  }
  catch (Exception $e) {
    $code = $e->getCode();
    $status = $e->getMessage();
    $error = "STATUS: $code - $status; ";
    $error .= "Communication with the Apigee endpoint is compromised. Cannot get API Products List.";
    if (user_access("administer organization settings")) {
      $error .= "<pre>" . $client->get_response_string() . "</pre>";
    }
    watchdog('devconnect_developer_apps', $error, array(), WATCHDOG_ERROR);
    return "<h4>" . $error . "</h4>";
  }
}

/**
 * Form constructor for adding/editing apps. Built via a menu callback to drupal_get_form().
 *
 * Incoming URL: user/%user/apps/add
 *
 * @return array
 */
function devconnect_developer_apps_edit_form($form, &$form_state, $account, $app_name = NULL) {
  module_load_include("module", "devconnect");
  $client = devconnect_default_api_client();
  $dc = new Apigee\ManagementAPI\DeveloperApp($client, $account->mail, (bool)variable_get('devconnect_appname_bug', FALSE));

  if (isset($app_name)) {
    try {
      $dc->load($app_name);
    } catch (Exception $e) {
      watchdog('devconnect_developer_apps', $e->getMessage(), array(), WATCHDOG_WARNING);
      drupal_not_found();
      exit;
    }
  }
  // Set Title
  if (isset($app_name)) {
    $header_caption = t('Editing App “@app”', array('@app' => $app_name));
    //drupal_set_title($header_caption);
    $button_caption = t('Save App');
  }
  else {
    drupal_set_title('Add App');
    $header_caption = 'App Add Form';
    $button_caption = t('Create App');
  }
  $owner_name = ($account->uid == $GLOBALS['user']->uid ? 'My' : $account->name . "'s");

  // Build Breadcrumbs
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l("$owner_name Apps", 'user/' . $account->uid . '/apps');


  // Set Breadcrumbs
  drupal_set_breadcrumb($breadcrumb);

  $form = array();

  $form['header'] = array(
    '#type' => 'legend',
    '#title' => $header_caption,
  );

  if (isset($app_name)) {
    $form['existing_machine_name'] = array(
      '#type' => 'item',
      '#title' => t('App Name'),
      '#markup' => check_plain($app_name),
      '#id' => 'existing_machine_name'
    );
    $form['machine_name'] = array(
      '#type' => 'value',
      '#value' => $app_name
    );

  }
  else {
    $form['machine_name'] = array(
      '#title' => t('App Name'),
      '#type' => 'textfield',
      '#id' => 'new_machine_name',
      '#default_value' => '',
      '#required' => TRUE,
      '#size'=> 145,
    );
  }
  // $form['access_type'] = array(
  //   '#title' => t('Access'),
  //   '#type' => 'select',
  //   '#id' => 'new_access_type',
  //   '#options' => array('none' => 'none', 'read' => 'read', 'write' => 'write', 'both' => 'both'),
  //   '#required' => TRUE,
  //   '#default_value' => (isset($app_details) ? $app_details['accessType'] : NULL),
  // );
  $form['callback_url'] = array(
    '#title' => t('Callback URL'),
    '#type' => 'textfield',
    '#id' => 'new_callback_url',
    '#default_value' => (isset($app_name) ? $dc->get_callback_url() : ''),
    '#required' => TRUE,
    '#size'=> 145,
  );

  // Invoke hook_devconnect_app_attributes to see if a custom module has
  // defined custom attributes to appear in this form.
  $custom_attributes = module_invoke_all('devconnect_app_attributes');
  foreach ($custom_attributes as $machine_name => $attribute) {
    $name = $attribute['name'];
    $default_value = (array_key_exists('default', $attribute) ? $attribute['default'] : NULL);
    $description = (array_key_exists('description', $attribute) ? $attribute['description'] : NULL);
    $required = (array_key_exists('required', $attribute) ? (bool) $attribute['required'] : FALSE);
    $max_length = (array_key_exists('maxlength', $attribute) ? $attribute['maxlength'] : NULL);
    $pattern = (array_key_exists('pattern', $attribute) ? $attribute['pattern'] : NULL);
    $tooltip = (array_key_exists('tooltip', $attribute) ? $attribute['tooltip']: NULL);
    $type = (array_key_exists('type', $attribute) ? $attribute['type'] : 'textfield');

    $form_field_name = 'attribute_' . $machine_name;

    if ($type == 'value') {
      $form[$form_field_name] = array('#type' => 'value', '#value' => $default_value);
    }
    else {
      if (isset($app_name)) {
        $default_value = $dc->get_attribute($machine_name);
      }

      $form[$form_field_name] = array(
        '#title' => t($name),
        '#type' => $type,
        '#default_value' => $default_value,
        '#required' => $required
      );
      if ($description) {
        $form[$form_field_name]['#description'] = t($description);
      }
      if ($max_length) {
        $form[$form_field_name]['#maxlength'] = $max_length;
      }
      if ($pattern) {
        $form[$form_field_name]['#attributes']['pattern'] = $pattern;
        $form[$form_field_name]['#element_validate'][] = 'devconnect_developer_apps_pattern_validate';
      }
      if ($tooltip) {
        $form[$form_field_name]['#attributes']['title'] = $tooltip;
      }
    }
  }

  try {
    $options = array();
    $api_product_obj = new \Apigee\ManagementAPI\APIProduct($client, (bool)variable_get('devconnect_appname_bug', FALSE));
    $api_products = $api_product_obj->list_products();
    foreach ($api_products as $api_product) {
      $options['prod-' . $api_product->get_name()] = $api_product->get_display_name();
    }
  }
  catch (Exception $e) {
    drupal_set_message($e->getMessage(), 'error');
    $options = array(); // TODO: come up with a more elegant way of handling this.
  }

  $preexisting_api_products = array();
  $api_product_default = array();
  $client_key = NULL;
  if (isset($app_name) && $dc->has_credential_info()) {
    $client_key = $dc->get_consumer_key();
    foreach ($dc->get_credential_api_products() as $api_product) {
      $api_product_default[] = 'prod-' . $api_product['apiproduct'];
      $preexisting_api_products[] = $api_product;
    }
    if (count($preexisting_api_products) > 0) {
      sort($preexisting_api_products);
    }
  }

  $form['preexisting_api_products'] = array(
    '#type' => 'value',
    '#value' => $preexisting_api_products
  );
  $form['client_key'] = array(
    '#type' => 'value',
    '#value' => $client_key
  );

  $form['api_product'] = array(
    '#title' => t('Product'),
    '#type' => 'select',
    '#id' => 'api_product',
    '#options' => $options,
    '#default_value' => $api_product_default,
    '#multiple' => TRUE,
    '#required' => FALSE, // Per Morgan, this will not always be required.
  );

  // Add jQuery Select List Plugin
  if ($path = libraries_get_path('jquery.selectlist')) {
    drupal_add_js($path . '/scripts/jquery.selectlist.pack.js');
    drupal_add_js(drupal_get_path('module', 'devconnect_developer_apps') . '/devconnect_developer_apps.js');
    drupal_add_css($path . '/css/selectlist.css');
    drupal_add_css(drupal_get_path('module', 'devconnect_developer_apps') . '/devconnect_developer_apps.css');
  }

//  if (count($options) == 1) {
//    $api_product = array_keys($options);
//    $form['api_product']['#default_value'] = array($api_product[0] => 1);
//    $form['api_product']['#access'] = FALSE;
//  }

  $form['uid'] = array(
    '#type' => 'value',
    '#id' => 'uid',
    '#value' => $account->uid,
  );

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => $button_caption,
    '#weight' => 10,
    '#submit' => array('devconnect_developer_apps_edit_form_submit')
  );

  $form['#validate'] = array('devconnect_developer_apps_edit_form_validate');

  // Set HTML5 required attribute on all required elements
  /*
  foreach ($form as $key => $value) {
    if (substr($key, 0, 1) != '#' && isset($value['#required']) && $value('#required')) {
      $form[$key]['#attributes']['required'] = 'required';
    }
  }
  */

  return $form;
}

function devconnect_developer_apps_pattern_validate($element, &$form_state, $form) {
  $pattern = '!' . preg_replace('!', '\\!', $element['#attributes']['pattern']) . '!';
  if (!preg_match($pattern, $element['#value'])) {
    form_error($element, t('The @title element does not conform to the indicated pattern.', array('@title' => $element['#title'])));
  }
}

function devconnect_developer_apps_edit_form_validate($form, &$form_state) {

  if ($form['machine_name']['#type'] == 'value') {
    // No need to validate existing machine names.
    return;
  }

  if (user_is_logged_in() && $form_state['values']['uid'] == $GLOBALS['user']->uid) {
    $user = $GLOBALS['user'];
  }
  else {
    $user = user_load($form_state['values']['uid']);
  }

  $machine_name = strtolower($form_state['values']['machine_name']);
  module_load_include("module", "devconnect");
  $client = devconnect_default_api_client();
  $dc = new Apigee\ManagementAPI\DeveloperApp($client, $user->mail, (bool)variable_get('devconnect_appname_bug', FALSE));

  // Assume app exists until proven otherwise
  $app_exists = TRUE;
  try {
    $dc->load($machine_name);
  }
  catch (Exception $e) {
    // Some sort of failure occurred, possibly indicating that app could not be retrieved.
    $app_exists = FALSE;
    watchdog('devconnect_developer_apps', $e->getMessage(), array(), WATCHDOG_NOTICE);
  }

  if ($app_exists) {
    // Throw form back to user.
    form_error($form['machine_name'], 'The App Name “' . check_plain($machine_name) . '” is already in use. Please select a different name.');
    watchdog('devconnect_developer_apps', "App $machine_name already exists.", array(), WATCHDOG_NOTICE);
  }
}

/**
 * Submit handler for the above form.
 *
 * @param $form
 * @param $form_state
 * @return bool
 */
function devconnect_developer_apps_edit_form_submit($form, &$form_state) {
  devconnect_developer_apps_hook('presave', $form_state);
  $values = $form_state['values'];

  if (user_is_logged_in() && $values['uid'] == $GLOBALS['user']->uid) {
    $values['user'] = $GLOBALS['user'];
  }
  else {
    $values['user'] = user_load($values['uid']);
  }
  module_load_include("module", "devconnect");
  $client = devconnect_default_api_client();
  $dc = new Apigee\ManagementAPI\DeveloperApp($client, $values['user']->mail, (bool)variable_get('devconnect_appname_bug', FALSE));

  try {
    if (arg(4) == 'edit-app') {
      $action_taken = 'Updated';
      $force_update = TRUE;
    }
    else {
      $action_taken = 'Created';
      $force_update = FALSE;
    }
    $dc->populate_from_form_values($values);
    $dc->save($force_update);
  }
  catch (\Apigee\Exceptions\ResponseException $e) {
    // The following should never occur. Name clashes should have been handled in form validation above.
    // If we encounter a name clash here, log it as CRITICAL -- these items MUST be addressed.
    if ($e->getCode() == 409) {
      drupal_set_message('The App Name “' . check_plain($values['machine_name']) . '” is already being used.', 'error');
      watchdog('devconnect_developer_apps', 'Duplicate app name "' . $values['machine_name'] . '" for user "' . $values['user']->name . '"!', array(), WATCHDOG_CRITICAL);
      //drupal_goto('user/' . $values['user']->uid . '/apps/add');
      return;
    }
    else {
      $action = rtrim(strtolower($action_taken), 'd');
      watchdog('devconnect_developer_apps', 'Saving app "' . $values['machine_name'] . '" for user "' . $values['user']->name . '" failed with HTTP status of ' . $e->getCode() . ". Details as follows:\n" . print_r($e->getParams(), TRUE), array(), WATCHDOG_ERROR);
      drupal_set_message('There was an error trying to ' . $action . ' the application. Details have been logged to the error log.', 'error', FALSE);
      return;
    }
  }
  catch (Exception $e) {
    $message = $e->getMessage();
    watchdog('devconnect_developer_apps', $message, array(), WATCHDOG_ERROR);
    drupal_set_message('The following error occurred while saving your app: <h4>' . $message . '</h4>', 'error');
    return;
  }
  drupal_set_message(t('App ' . $action_taken . '!'), 'status');

  $middle_arg = (module_exists('me') && user_is_logged_in() && $values['uid'] == $GLOBALS['user']->uid ? 'me' : $values['uid']);

  $form_state['redirect'] = 'user/' . $middle_arg . '/apps';
  $form_state['storage']['app'] =& $dc;

  $results = $dc->get_debug_data();

  // Invoke hook_devconnect_developer_app_save on all implementing modules
  devconnect_developer_apps_hook('save', $form_state, $results);
}

/**
 * Form constructor for deleting apps. This is called from a menu callback via drupal_get_form.
 *
 * Incoming URL takes the following form:
 * - user/%user/apps/%/delete
 *
 * @return array
 */
function devconnect_developer_app_delete_form() {

  drupal_set_title(t('Are you sure?'));

  $form = array(
    '#type' => 'form',
    '#attributes' => array(
      'id' => 'devconnect_developer_application_delete',
    ),
  );
  $form['are_you_sure'] = array(
    '#markup' => 'Deleting the ‘' . arg(3) . '’ app will also delete all of its data. This action cannot be undone.<br><br>',
  );

  $form['application'] = array('#type' => 'value', '#value' => arg(3));
  $form['uid'] = array('#type' => 'value', '#value' => arg(1));

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Delete App'),
    '#weight' => 10,
    '#submit' => array('devconnect_developer_app_delete_form_submit'),
  );

  $user_arg = arg(1);
  if (user_is_logged_in() && $GLOBALS['user']->uid == $user_arg && module_exists('me')) {
    $user_arg = 'me';
  }

  $form['actions']['cancel'] = array(
    '#markup' => l(t('Cancel'), 'user/' . $user_arg . '/apps', array('attributes' => array('class' => array('cancel-link btn')))),
    '#weight' => 11,
  );

  return $form;
}

/**
 * Form submit handler for the above form.
 *
 * @param $form
 * @param $form_state
 */
function devconnect_developer_app_delete_form_submit(&$form, &$form_state) {
  $values = $form_state['values'];

  if (user_is_logged_in() && $values['uid'] == $GLOBALS['user']->uid) {
    $values['user'] = $GLOBALS['user'];
  }
  else {
    $values['user'] = user_load($values['uid']);
  }

  $result = NULL;
  try {
    module_load_include("module", "devconnect");
    $client = devconnect_default_api_client();
    $dc = new Apigee\ManagementAPI\DeveloperApp($client, $values['user']->mail, (bool)variable_get('devconnect_appname_bug', FALSE));

    // Invoke hook_devconnect_developer_app_predelete on all implementing modules.
    devconnect_developer_apps_hook('predelete', $form_state);

    $dc->delete($values['application']);
    $result = $dc->get_debug_data();
    drupal_set_message(t('App Deleted!'), 'status');
  } catch (Exception $e) {
    watchdog('devconnect_developer_apps', $e->getMessage(), array(), WATCHDOG_ERROR);
    drupal_set_message(t('App could not be deleted.'), 'error');
  }

  $middle_arg = (module_exists('me') && user_is_logged_in() && $values['uid'] == $GLOBALS['user']->uid ? 'me' : $values['uid']);
  $form_state['redirect'] = 'user/' . $middle_arg . '/apps';
  if (isset($result)) {
    // Invoke hook_devconnect_developer_app_delete on all implementing modules.
    devconnect_developer_apps_hook('delete', $form_state, $result);
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * @param array $data
 * @param $router_item
 * @param $root_path
 */
function devconnect_developer_apps_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if (arg(0) == 'user') {
    unset($data['tabs']);
  }
}

/**
 * Page callback to display detailed info for a user's app.
 *
 * @param $user
 * @param $app_name
 * @return string
 */
function devconnect_developer_apps_detail($user, $app_name) {
  module_load_include("module", "devconnect");
  $client = devconnect_default_api_client();
  $dc = new Apigee\ManagementAPI\DeveloperApp($client, $user->mail, (bool)variable_get('devconnect_appname_bug', FALSE));

  try {
    $dc->load($app_name);
  }
  catch (Exception $e) {
    return '<h4>' . $e->getMessage() . '</h4>';
  }
  $description = $dc->get_description();
  if (!empty($description)) {
    devconnect_developer_apps_set_description($description);
  }

  // Build Breadcrumbs
  $owner_name = ($user->uid == $GLOBALS['user']->uid ? 'My' : $user->name . "'s");
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l("$owner_name Apps", 'user/' . $user->uid . '/apps');

  $access_type = $dc->get_access_type();
  $raw_result = $dc->get_debug_data();

  $info = array(
    'account' => $user,
    'access_type' => ( $access_type == 'both' ? 'read/write' : $access_type),
    'callback_url' => $dc->get_callback_url(),
    'name' => $dc->get_name(),
    'status' => $dc->get_status(),
    'attributes' => array(),
    'credentials' => array(),
    'page_title' => $dc->get_name(),
    'breadcrumb' => $breadcrumb,
    'raw_data' => $raw_result['data'],
    'analytics_chart' => FALSE
  );

  $cred = array('apiproducts' => array());
  $api_product_obj = new Apigee\ManagementAPI\APIProduct($client, (bool)variable_get('devconnect_appname_bug', FALSE));
  foreach ($dc->get_credential_api_products() as $api_product) {
    try {
      $api_product_obj->load($api_product['apiproduct']);
      $cred['apiproducts'][] = array(
        'display_name' => $api_product_obj->get_display_name(),
        'description' => $api_product_obj->get_description(),
        'status' => $api_product['status'],
        'name' => $api_product['apiproduct']
      );
    }
    catch (Exception $e) {
      //TODO: do something here
    }
  }
  $cred['consumer_key'] = $dc->get_consumer_key();
  $cred['consumer_secret'] = $dc->get_consumer_secret();
  $cred['status'] = $dc->get_credential_status();
  $cred['scopes'] = $dc->get_credential_scopes();
  $info['credentials'][] = $cred;

  $info['app_attributes'] = _devconnect_developer_apps_get_attributes($dc->get_attributes());
  if (devconnect_developer_apps_show_analytics($cred)) {
    module_load_include('inc', 'devconnect_developer_apps', 'analytics');
    $info['analytics_chart'] = devconnect_developer_apps_analytics_performance($app_name);
  }

  // Invoke hook_devconnect_developer_app_alter on this info
  drupal_alter('devconnect_developer_app', $info);

  // Set Title
  drupal_set_title($info['page_title']);
  // Set Breadcrumbs
  drupal_set_breadcrumb($info['breadcrumb']);

  return theme('devconnect_developer_app', $info);
}

/**
 * Helper function to get displayable attributes.
 *
 * @param $app_attributes
 * @return array
 */
function _devconnect_developer_apps_get_attributes($app_attributes) {
  // Invoke custom hook
  $shown_attributes = module_invoke_all('devconnect_attributes_display_list');
  $items = array();
  foreach ($shown_attributes as $attr_name => $attr_display) {
    foreach ($app_attributes as $result_attr_name => $result_attr_value) {
      if ($result_attr_name == $attr_name) {
        $items[$attr_display] = $result_attr_value;
      }
    }
  }
  return $items;
}

/**
 * Preprocessor for theme('page').
 *
 * @param $variables
 * @return void
 */
function devconnect_developer_apps_preprocess_page(&$variables){
  $description = devconnect_developer_apps_set_description();
  if (isset($description)) {
    $variables['subtitle'] = $description;
  }
}

/**
 * Static getter/setter for app description
 *
 * @param string|null $description
 * @return string|null
 */
function devconnect_developer_apps_set_description($description = NULL) {
  static $desc;
  if (isset($description)) {
    $desc = $description;
  }
  return $desc;
}

/**
 * Helper function to determine if the Performance tab should be shown.
 *
 * @param $credential
 * @return bool
 */
function devconnect_developer_apps_show_analytics($credential) {
  // NOTE: We used to check here to see if one of the API Products associated
  // with the given credential required an OAuth Token, under the mistaken
  // assumption that only OAuth-enabled apps generate analytics data. However,
  // this assumption has proven false; any app that authenticates with a key
  // generates the data.
  // If you want to see the code that was here, look in git versions prior to
  // 25-Jan-2013.
  return variable_get('devconnect_show_analytics', FALSE);
}

function devconnect_developer_apps_hook($hook, &$values, $kms_result = NULL) {
  $hook = 'devconnect_developer_app_' . $hook;

  // Cannot use module_invoke_all because $values must be passed by reference.
  foreach (module_implements($hook) as $module) {
    $function = $module . '_' . $hook;
    if (isset($kms_result)) {
      // Note that for backwards compatibility, $kms_result must be first arg
      $function($kms_result, $values);
    }
    else {
      $function($values);
    }
  }
}
