<?php
/**
 * @file
 * Code for the devconnect_default_content feature.
 */

include_once 'devconnect_default_content.features.inc';


function devconnect_default_content_block_info() {
  $blocks = array();
  
  $blocks['footer'] = array(
     'info' => t('Site-wide Default Footer'),
     'status' => false,
     'region' => 'footer',
     'visibility' => BLOCK_VISIBILITY_NOTLISTED,
     'pages' => 'admin/*'
   );
  
   $blocks['develop-with-these'] = array(
      'info' => t('Develop With These'),
      'status' => false,
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
      'pages' => 'admin/*'
    );
  
  return $blocks;
}

function devconnect_default_content_block_view($delta = '') {
  $theme_path = base_path().drupal_get_path("theme", "apigee_base");
  switch($delta) {
    case "footer":
      return array(
        "subject" => "",
        "content" => '<div class="navbar">
            <div class="navbar-inner">
              <div class="container">
                <ul class="social-media-links nav span3">
                  <li class="first"><a href="https://twitter.com/apigee" target="_blank"><img src="'.$theme_path.'/images/twiiter-icon.png" alt="Twitter" /></a></li>
                  <li><a href="http://www.facebook.com/apigee" target="_blank"><img src="'.$theme_path.'/images/facebook-icon.png" alt="Facebook" /></a></li>
                  <li class="last"><a href="http://www.linkedin.com/company/apigee" target="_blank"><img src="'.$theme_path.'/images/linkedin-icon.png" alt="LinkedIn" /></a></li>
                </ul>
                <ul class="footer-links nav span10">
                  <li class="first"><a href="privacy-policy">Privacy Policy</a></li>
                  <li class="divider-vertical"></li>
                  <li><a href="terms-use">Terms &amp; Use</a></li>
                  <li class="divider-vertical"></li>
                  <li class="last"><a href="contact-us">Contact</a></li>
                </ul>
                <!--<div class="footer-logo span2 pull-right">
                  <a href="http://apigee.com/"><img src="'.$theme_path.'/images/footer-logo.png" /></a>
               </div>-->
              </div>
            </div>
          </div>');
          break;
      case "apis":
        return array(
          "subject" => t("Develop with these APIs"),
          "content" => '<div class="starter api">
                        <h3><a href="/documentation">Starter API</a></h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed mi turpis. Maecenas viverra consequat ipsum.</p>
                        </div>
                        <div class="provider api">
                        <h3><a href="/documentation">Provider API</a></h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed mi turpis. Maecenas viverra consequat ipsum.</p>
                        </div>'
            );
        break;
      
      default: 
        return array();
  }
  
}
