<?php
/**
 * @file
 * devconnect_default_content.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function devconnect_default_content_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Mobile APIs',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '00ea6f28-1d51-4b20-99c3-7bdc6abf8640',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'API versioning',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '16dfc147-f7bb-4f03-b257-a2b200b14d73',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'API analytics and metrics',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '1e1ff589-790d-4d85-951a-e91259ed4299',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'API strategy',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '45492312-4685-4403-ad9e-d1612a17dde5',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'REST API Design',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '4711c626-8346-488c-8095-be3b3012fdd5',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'API scalability',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '7f4c22a0-fd5a-46e7-91c7-1d0ab83d6f98',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'API security',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => 'a344b1ab-73f8-43f8-a1a9-d125c11b8431',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Oauth 1.0a and 2.0',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => 'd7234573-2c6a-4580-8749-17cd0826e966',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'API product management',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => 'd8cce843-0511-43ac-ba83-e0ce8cb020ef',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Replace Me',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => 'd9b7b4d9-78a5-4f2e-86a6-470521f7fe4f',
    'vocabulary_machine_name' => 'tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'API virtualization',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => 'f1de4fa2-0abf-4815-a239-9e7a10192d43',
    'vocabulary_machine_name' => 'blog',
    'metatags' => array(),
  );
  return $terms;
}
