<?php
/**
 * @file
 * Contains functionality related to Apigee profile updates.
 */

/**
 * Implements hook_admin_menu_output_alter().
 *
 * Moves the environment indicator to the left of user-switcher dropdown which
 * appears when devel and admin_menu modules are enabled.
 */
function apigee_profile_updates_admin_menu_output_alter(array &$content) {
  if (array_key_exists('account', $content) && array_key_exists('environment_indicator', $content)) {
    $weight = $content['account']['#weight'];
    $content['environment_indicator']['#weight'] = $weight + 1;
  }
}

/**
 * Implements hook_filter_info_alter().
 *
 * Removes Display Suite and PHP Code filters if they are enabled, because
 * they expose security vulnerabilities.
 */
function apigee_profile_updates_filter_info_alter(&$info) {
  if (array_key_exists('ds_code', $info)) {
    unset($info['ds_code']);
  }
  if (array_key_exists('php_code', $info)) {
    unset($info['php_code']);
  }
}

/**
 * Implements hook_form_alter().
 */
function apigee_profile_updates_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login') {
    $form['userpasswordlink'] = array(
      '#markup' => '<br>' . l(t('Forgot your password?'), 'user/password') . '<br><br>',
      '#weight' => 100,
    );
  }
  elseif ($form_id == 'user_admin_settings') {
    // Check to see if the active theme is apigee_responsive or one of its
    // subthemes.
    $theme_name = variable_get('theme_default');
    $is_apigee_responsive = FALSE;
    while (TRUE) {
      if ($theme_name == 'apigee_responsive') {
        $is_apigee_responsive = TRUE;
        break;
      }
      $theme = system_get_info('theme', $theme_name);
      if (empty($theme['base theme'])) {
        break;
      }
      $theme_name = $theme['base theme'];
    }
    // If we are using apigee_responsive or a subtheme thereof, invoke an extra
    // submit handler.
    if ($is_apigee_responsive) {
      $form_state['storage']['previous_user_register'] = $form['registration_cancellation']['user_register']['#default_value'];
      $form['#submit'][] = 'apigee_profile_updates_user_admin_settings_submit';
    }
  }
}

/**
 * Extra submit handler for user_admin_settings form.
 *
 * If the user_register value changed, purge all cached pages, because we
 * want the "Register" link to immediately disappear/reappear as appropriate.
 * Note that because the user-agent may have cached certain pages, a browser
 * hard-refresh may be necessary to complete this process.
 *
 * @param array $form
 *   Descriptor of the form being submitted.
 * @param array $form_state
 *   State of the form being submitted.
 */
function apigee_profile_updates_user_admin_settings_submit($form, &$form_state) {
  if ($form_state['values']['user_register'] != $form_state['storage']['previous_user_register']) {
    cache_clear_all('*', 'cache_page', TRUE);
  }
}

/**
 * Gets the version of the current release.
 *
 * Get the release version from the buildInfo file if present,
 * or else from the version of the devconnect module.
 *
 * @return string
 *   The current version of this release.
 */
function apigee_profile_updates_get_build_version($user_agent = NULL) {
  static $build_version;
  if (!isset($build_version)) {
    $extra = (strpos($user_agent, ' (SAML)') === FALSE ? '' : ' (SAML)');

    $build_info = FALSE;
    if (file_exists(DRUPAL_ROOT . '/buildInfo')) {
      $build_info = DRUPAL_ROOT . '/buildInfo';
    }
    elseif (file_exists(DRUPAL_ROOT . '/profiles/apigee/buildInfo')) {
      $build_info = DRUPAL_ROOT . '/profiles/apigee/buildInfo';
    }
    $build_version = FALSE;
    if ($build_info) {
      $fp = fopen($build_info, 'r');
      $line = trim(fgets($fp));
      fclose($fp);
      if (preg_match('!([0-9.]{2,})$!', $line, $matches)) {
        $build_version = 'DevPortal/' . $matches[1] . $extra;
      }
    }
    if (!$build_version) {
      $info = system_get_info('module', 'devconnect');
      if (!empty($info)) {
        $build_version = 'devconnect/' . $info['version'] . $extra;
      }
    }
    if (!$build_version) {
      if (empty($user_agent)) {
        $build_version = 'Drupal/' . VERSION . ';PHP/' . PHP_VERSION;
      }
      else {
        $build_version = $user_agent;
      }
    }
  }
  return $build_version;
}

/**
 * Implements hook_devconnect_user_agent_alter().
 */
function apigee_profile_updates_devconnect_user_agent_alter(&$user_agent) {
  $user_agent = apigee_profile_updates_get_build_version($user_agent);
}

/**
 * Implements hook_menu_alter().
 *
 * Denies access to PHP execution URL in the devel module if it is enabled.
 */
function apigee_profile_updates_menu_alter(&$items) {
  if (isset($items['devel/php'])) {
    $items['devel/php']['access callback'] = FALSE;
  }
}
